# Лабораторная работа 0  
## Задание

### Цель
Освоить базовые операции в PyTorch и понять механизм вычисления градиентов.

---

### Что нужно сделать

1. Настроить среду:
   - установить PyTorch, Jupyter, NumPy, Matplotlib  
   - запустить Jupyter Notebook  

2. Реализовать работу с тензорами:
   - создать 2 тензора  
   - выполнить:
     - сложение  
     - транспонирование  
     - матричное умножение  
   - оформить понятный вывод результатов  

3. Разобрать градиенты:
   - задать тензор с `requires_grad=True`  
   - вычислить простую функцию  
   - вызвать `.backward()`  
   - вывести градиент  

4. Дать краткое пояснение:
   - как PyTorch считает градиенты  
   - где используются тензоры и градиенты  

---

### Результат

Ноутбук с:
- кодом  
- выводами  
- краткими пояснениями  


# Операции с тензорами

In [3]:
import torch

# Создание тензоров
tensor_a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
tensor_b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

# Операции
tensor_sum = tensor_a + tensor_b
tensor_transpose = tensor_a.T
tensor_matmul = torch.matmul(tensor_a, tensor_b)

# Функция для красивого вывода
def print_tensor(name, tensor):
    print(f"{name}:")
    print(tensor)
    print("-" * 30)

# Вывод
print_tensor("Tensor A", tensor_a)
print_tensor("Tensor B", tensor_b)
print_tensor("A + B", tensor_sum)
print_tensor("A^T (transpose)", tensor_transpose)
print_tensor("A @ B (matrix multiplication)", tensor_matmul)

Tensor A:
tensor([[1., 2.],
        [3., 4.]])
------------------------------
Tensor B:
tensor([[5., 6.],
        [7., 8.]])
------------------------------
A + B:
tensor([[ 6.,  8.],
        [10., 12.]])
------------------------------
A^T (transpose):
tensor([[1., 3.],
        [2., 4.]])
------------------------------
A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])
------------------------------


# Вычисление градиентов

In [ ]:
#1
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x + 1
y.backward()
print("\ny = x^3 + 2x + 1")
print("Gradient:", x.grad)

#2
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x + 1
y.backward()
print("\ny = x^3 + 2x + 1")
print("Gradient:", x.grad)


3#
x = torch.tensor(2.0, requires_grad=True)
z = torch.tensor(3.0, requires_grad=True)
y = x**2 + z**2 + x*z
y.backward()
print("\ny = x^2 + z^2 + x*z")
print("dy/dx:", x.grad)
print("dy/dz:", z.grad)


y = x^3 + 2x + 1
Gradient: tensor(14.)

y = x^3 + 2x + 1
Gradient: tensor(14.)

y = x^2 + z^2 + x*z
dy/dx: tensor(7.)
dy/dz: tensor(8.)


---
### Как PyTorch считает градиенты

PyTorch использует автоматическое дифференцирование (autograd).

Во время вычисления функции:
- строится вычислительный граф
- все операции записываются

При вызове `.backward()`:
- выполняется обратное распространение ошибки (backpropagation)
- вычисляются производные по всем параметрам с `requires_grad=True`

Градиенты сохраняются в поле:
- `tensor.grad`

---
### Тензоры

Тензоры — основная структура данных PyTorch.

Используются для:
- входных данных (изображения, текст, признаки)
- параметров моделей (веса, смещения)
- промежуточных вычислений
- выходов модели

---

### Градиенты

Градиенты используются для обучения моделей.

Они показывают:
- как изменить параметры, чтобы уменьшить loss

Пример цикла обучения:

```python
loss = criterion(y_pred, y_true)

optimizer.zero_grad()
loss.backward()
optimizer.step()
```
---